// Genera un ledger di esempio col serializer e lo scrive su stdout,
// per validarlo con bean-check (vedi npm run / docs).

import type { Directive } from "@unportfolio/core/beancount/ast";
import { formatDirective } from "@unportfolio/core/beancount/serializer";
import { Decimal } from "decimal.js";

const D = (n: string | number) => new Decimal(n);

const directives: Directive[] = [
  { kind: "option", name: "title", value: "unportfolio sample" },
  { kind: "option", name: "operating_currency", value: "EUR" },
  { kind: "raw", src: "\n" },
  {
    kind: "open",
    date: "2024-01-01",
    account: "Assets:Broker:Directa:Cash",
    currencies: ["EUR"],
    meta: {},
  },
  {
    kind: "open",
    date: "2024-01-01",
    account: "Assets:Broker:Directa:VWCE",
    currencies: ["VWCE"],
    booking: "FIFO",
    meta: {},
  },
  {
    kind: "open",
    date: "2024-01-01",
    account: "Assets:Broker:Directa:IT0005547408",
    currencies: ["IT0005547408"],
    meta: {},
  },
  {
    kind: "open",
    date: "2024-01-01",
    account: "Equity:Conferimenti",
    currencies: ["EUR"],
    meta: {},
  },
  {
    kind: "open",
    date: "2024-01-01",
    account: "Income:Coupons:IT0005547408",
    currencies: ["EUR"],
    meta: {},
  },
  {
    kind: "open",
    date: "2024-01-01",
    account: "Income:CapitalGains:VWCE",
    currencies: ["EUR"],
    meta: {},
  },
  {
    kind: "open",
    date: "2024-01-01",
    account: "Expenses:Fees:Broker",
    currencies: ["EUR"],
    meta: {},
  },
  {
    kind: "open",
    date: "2024-01-01",
    account: "Expenses:Taxes:Withholding",
    currencies: ["EUR"],
    meta: {},
  },
  { kind: "raw", src: "\n" },
  {
    kind: "commodity",
    date: "2024-01-01",
    currency: "IT0005547408",
    meta: {
      name: "BTP VALORE GN27 EUR",
      isin: "IT0005547408",
      class: "BOND",
      maturity: "2027-06-06",
      "coupon-rate": "0.0333",
      "coupon-freq": "4",
      "tax-rate": "0.125",
      "price-source": "borsa-italiana:IT0005547408.MOT",
    },
  },
  { kind: "raw", src: "\n" },
  {
    kind: "transaction",
    date: "2024-02-12",
    flag: "*",
    payee: "Directa",
    narration: "Conferimento con bonifico",
    tags: [],
    links: [],
    meta: {},
    postings: [
      {
        account: "Assets:Broker:Directa:Cash",
        amount: { number: D(4000), currency: "EUR" },
        meta: {},
      },
      { account: "Equity:Conferimenti", amount: { number: D(-4000), currency: "EUR" }, meta: {} },
    ],
  },
  {
    kind: "transaction",
    date: "2024-02-26",
    flag: "*",
    payee: "Directa",
    narration: "Acquisto VWCE",
    tags: [],
    links: [],
    meta: { ordine: "Q5710082457287" },
    postings: [
      {
        account: "Assets:Broker:Directa:VWCE",
        amount: { number: D(2), currency: "VWCE" },
        cost: { number: D("114.19"), currency: "EUR" },
        meta: {},
      },
      {
        account: "Assets:Broker:Directa:Cash",
        amount: { number: D("-228.38"), currency: "EUR" },
        meta: {},
      },
    ],
  },
  {
    kind: "transaction",
    date: "2024-02-26",
    flag: "*",
    payee: "Directa",
    narration: "Commissioni ordine",
    tags: [],
    links: [],
    meta: { ordine: "Q5710082457287" },
    postings: [
      { account: "Expenses:Fees:Broker", amount: { number: D("1.50"), currency: "EUR" }, meta: {} },
      {
        account: "Assets:Broker:Directa:Cash",
        amount: { number: D("-1.50"), currency: "EUR" },
        meta: {},
      },
    ],
  },
  {
    // bond: lotti da 100 di nominale → 5.000 EUR nominale = 50 unità, prezzo % = prezzo unitario
    kind: "transaction",
    date: "2024-06-03",
    flag: "*",
    payee: "Directa",
    narration: "Acquisto BTP VALORE GN27",
    tags: [],
    links: [],
    meta: {},
    postings: [
      {
        account: "Assets:Broker:Directa:IT0005547408",
        amount: { number: D(50), currency: "IT0005547408" },
        cost: { number: D("99.20"), currency: "EUR" },
        meta: {},
      },
      {
        account: "Assets:Broker:Directa:Cash",
        amount: { number: D(-4960), currency: "EUR" },
        meta: {},
      },
    ],
  },
  {
    kind: "transaction",
    date: "2025-06-10",
    flag: "*",
    payee: "Directa",
    narration: "Cedola obb.",
    tags: [],
    links: [],
    meta: {},
    postings: [
      {
        account: "Assets:Broker:Directa:Cash",
        amount: { number: D("41.63"), currency: "EUR" },
        meta: {},
      },
      {
        account: "Income:Coupons:IT0005547408",
        amount: { number: D("-41.63"), currency: "EUR" },
        meta: {},
      },
    ],
  },
  {
    kind: "transaction",
    date: "2025-06-10",
    flag: "*",
    payee: "Directa",
    narration: "Rit.cedola obb.",
    tags: [],
    links: [],
    meta: {},
    postings: [
      {
        account: "Expenses:Taxes:Withholding",
        amount: { number: D("5.20"), currency: "EUR" },
        meta: {},
      },
      {
        account: "Assets:Broker:Directa:Cash",
        amount: { number: D("-5.20"), currency: "EUR" },
        meta: {},
      },
    ],
  },
  {
    kind: "transaction",
    date: "2025-07-01",
    flag: "*",
    payee: "Directa",
    narration: "Vendita VWCE",
    tags: [],
    links: [],
    meta: {},
    postings: [
      {
        account: "Assets:Broker:Directa:VWCE",
        amount: { number: D(-1), currency: "VWCE" },
        cost: {},
        price: { kind: "unit", amount: { number: D(130), currency: "EUR" } },
        meta: {},
      },
      {
        account: "Assets:Broker:Directa:Cash",
        amount: { number: D(130), currency: "EUR" },
        meta: {},
      },
      { account: "Income:CapitalGains:VWCE", meta: {} },
    ],
  },
  { kind: "raw", src: "\n" },
  {
    kind: "price",
    date: "2025-07-01",
    currency: "VWCE",
    amount: { number: D("131.42"), currency: "EUR" },
    meta: {},
  },
  {
    kind: "price",
    date: "2025-07-01",
    currency: "IT0005547408",
    amount: { number: D("99.85"), currency: "EUR" },
    meta: {},
  },
  { kind: "raw", src: "\n" },
  {
    kind: "balance",
    date: "2025-07-02",
    account: "Assets:Broker:Directa:Cash",
    amount: { number: D("-1023.45"), currency: "EUR" },
    meta: {},
  },
];

process.stdout.write(directives.map(formatDirective).join(""));
